name: Daily News PDF & Emailer

on:
  schedule:
    - cron: '30 19 * * *' # Runs at 1:00 AM IST daily
  workflow_dispatch:

jobs:
  run-curator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install feedparser reportlab

      - name: Run Curator Script
        env:
          SENDER_EMAIL: ${{ secrets.rohith29806@gmail.com }}
          EMAIL_APP_PASSWORD: ${{ secrets.reum nlkg owrg xsjs }}
          RECEIVER_EMAIL: ${{ secrets.rohith29806@gmail.com }}
        run: |
          python curator.py
